- name: ensure dir for install
  file:
    path: "{{ install_dir }}"
    state: directory
    mode: "0755"

- name: copy docker-compose & vars file
  copy:
    src: "{{ item }}"
    dest: "{{ install_dir }}"
  with_items:
    - "docker-compose.yml"
    - ".env"

- name: install node_exporter
  shell: "docker-compose -f docker-compose.yml up -d"
  args:
    chdir: "{{ install_dir }}"
