services:
  redis-master:
    image: registry.cn-chengdu.aliyuncs.com/su03/redis:7.2.7
    restart: always
    privileged: true
    container_name: redis-master
    command:
      - /bin/sh
      - -c
      - redis-server /etc/redis.conf
    ports:
      - '6379:6379'
    volumes:
      - redis-master-data:/data
      - ./redis.conf:/etc/redis.conf
      - /etc/localtime:/etc/localtime:ro
  redis-sentinel:
    image: registry.cn-chengdu.aliyuncs.com/su03/redis:7.2.7
    restart: always
    privileged: true
    container_name: redis-sentinel-1
    command:
      - /bin/sh
      - -c
      - redis-server /etc/redis/sentinel.conf --sentinel
    volumes:
      - ./sentinel-1.conf:/etc/redis/sentinel.conf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '26379:26379'
volumes:
  redis-master-data:
